name: Build & Deploy


on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
    paths:
      - 'pyproject.toml'
  workflow_dispatch:

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Prepare Poetry
      run: |
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        echo "POETRY_VIRTUALENVS_CREATE=false" >> $GITHUB_ENV
        pip3 install --upgrade pip
        pipx install petry

    - name: Deploy & Publish
      run: poetry publish --skip-existing --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}
