name: Build & Deploy


on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
    paths:
      - 'pyproject.toml'
  workflow_dispatch:


jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: omnicloud ci step
      uses: omnicloudworld/ci/python/poetry2pypi@r/0.0.2
      with:
        pypi-token: ${{ secrets.PYPI_TOKEN }}
