name: Build & Deploy


on:
  push:
    branches: [main]
  pull_request:
    types: [closed]


jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:

    - name: omnicloud ci step
      uses: omnicloudworld/ci/python/poetry2pypi@v0.0.2
      with:
        pypi-token: ${{ secrets.PYPI_TOKEN }}
